### ISSUE TITLE
原始输入转变为protobuf消息问题

### ISSUE THREAD

**Issue by WhereIsOops** [Kiprey/protobuf_ctf_fuzz#1]
在LPM代码中使用了LoadProtoInput将原始输入转变为protobuf格式的消息，请教下对原始输入有怎么样的类型要求呢？
我尝试从文件中读取数据保存为string，并把他转化为protobuf消息但是失败了
![image](https://user-images.githubusercontent.com/95118965/145766516-571be8a9-739e-4270-a977-453dacaffbdd.png)

或者作者你有什么方法可以调试protobuf吗，这困扰了我一段时间了。。非常感谢

**Comment by Kiprey** [comment]
原始输入，必须符合 Protobuf Message 的二进制格式数据。
通俗一点就是原始的语料必须手动用 dump.cc 生成一些出来。

调试 protobuf，我使用 gdb 单步跟踪进行调试。编译时加上 `-g3 -ggdb3` 标志，这样在 gdb 调试时就有符号和源码。

**Comment by WhereIsOops** [comment]
> 原始输入，必须符合 Protobuf Message 的二进制格式数据。 通俗一点就是原始的语料必须手动用 dump.cc 生成一些出来。
> 
> 调试 protobuf，我使用 gdb 单步跟踪进行调试。编译时加上 `-g3 -ggdb3` 标志，这样在 gdb 调试时就有符号和源码。

看你的dumper.cc文件中，有写从argv[1]中获取输入，转换为对应的protobuf数据，这一步对argv[1]有什么要求吗

**Comment by Kiprey** [comment]
这里的 argv[1] 要求的必须是 protobuf Message 的二进制格式数据。
例如没带参数跑 dump 所生成的 protobuf binary 文件。[#L105](https://github.com/Kiprey/protobuf_ctf_fuzz/blob/main/kp_src/dumper.cc#L105)

**Comment by WhereIsOops** [comment]
大佬我又来求助了Orz，lpm的mutate应该怎么用啊，我写了下面这个测试代码但是直接coredump

#include "compare.pb.h"
#include "src/mutator.h"
#include <bits/stdc++.h>

using std::cin;
using std::cout;
using std::endl;

class MyMutator : public protobuf_mutator::Mutator {
};


int main(int argc, char *argv[])
{
    TEST t;
    t.set_a(101);
    t.set_b("testtest");
    cout << t.a() << endl;
    cout << t.b() << endl;

    static MyMutator mutator;
    mutator.Seed(1);
    mutator.Mutate(&t, 100);
    cout << t.a() << endl;
    cout << t.b() << endl;

    return 0;
}
Then use the following method to compile： clang++ compare.cc compare.pb.cc -lprotobuf -lprotobuf-mutator -L /usr/local/lib/ -I /usr/local/include/libprotobuf-mutator

A coredump occurs during the running.
#0 0x00000000004304d5 in TEST_default_instance ()
#1 0x000000000041137c in google::protobuf::Message::GetDescriptor (this=0x7fffffffe328) at external.protobuf/include/google/protobuf/message.h:356
#2 0x000000000040d72e in protobuf_mutator::(anonymous namespace)::CastToAny (message=0x7fffffffe328) at ../src/mutator.cc:387
#3 0x000000000040d6da in protobuf_mutator::(anonymous namespace)::UnpackIfAny (message=warning: RTTI symbol not found for class 'TEST'
...) at ../src/mutator.cc:399
#4 0x000000000040aecd in protobuf_mutator::(anonymous namespace)::UnpackAny (message=warning: RTTI symbol not found for class 'TEST'
..., result=0x7fffffffe250) at ../src/mutator.cc:404
#5 0x000000000040b688 in protobuf_mutator::Mutator::Mutate (this=0x4306e0 main::mutator, message=0x7fffffffe328, max_size_hint=100) at ../src/mutator.cc:639
#6 0x0000000000406d55 in main ()
#7 0x00007ffff77c70b3 in __libc_start_main (main=0x406b80

, argc=1, argv=0x7fffffffe468, init=, fini=, rtld_fini=, stack_end=0x7fffffffe458) at ../csu/libc-start.c:308
#8 0x0000000000406abe in _start ()

**Comment by Kiprey** [comment]
这个，我建议你先定位一下 core dump 的触发点，以及触发条件，之后再一步步往上回溯找原因（捂脸）
因为我这边也不方便肉眼调试.......
